name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.cf_waiter_menu }}
        run: git push --force https://pennywa:$HF_TOKEN@huggingface.co/spaces/pennywa/AI_Waiter_Chatbot main
